import { createContext, useContext, useState, useEffect } from 'react'

const translations = {
  en: {
    // Nav
    home: 'Home',
    tripPlanner: 'Trip Planner',
    itinerary: 'Itinerary',
    map: 'Map',
    profile: 'Profile',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    signOut: 'Sign Out',
    arabic: 'عربي',
    english: 'English',

    // Hero
    heroTag: '⚡ AI-Powered Travel Planning',
    heroTitle: 'Plan Your Perfect Trip in Saudi Arabia with AI',
    heroBrand: 'Shawaf — شواف',
    heroSub: 'Enjoy smart, personalized trip planning powered by the latest AI technology. Create detailed daily itineraries that match your preferences and budget across Saudi Arabia.',
    startPlanning: 'Start Planning Your Trip →',
    learnMore: 'Learn More',
    rating: '4.9',
    ratingLabel: 'User Rating',
    cities: '30+',
    citiesLabel: 'Covered Cities',
    travelers: '12K+',
    travelersLabel: 'Happy Travelers',
    trips: '50K+',
    tripsLabel: 'Trips Generated',

    // Features
    whyChoose: 'Why Choose Shawaf?',
    feat1Title: 'AI-Powered Planning',
    feat1Desc: 'Our advanced AI generates personalized itineraries based on your unique preferences, travel style, and budget.',
    feat2Title: 'Interactive Maps',
    feat2Desc: 'Visualize your journey with integrated maps showing all attractions, distances, and optimal routes.',
    feat3Title: 'Smart Scheduling',
    feat3Desc: 'Automatically optimize your schedule based on opening hours, travel times, and attraction priorities.',
    feat4Title: 'PDF Export',
    feat4Desc: 'Download your complete itinerary as a beautifully formatted PDF to take offline anywhere.',
    feat5Title: 'Multi-City Trips',
    feat5Desc: 'Plan complex multi-city journeys across Saudi Arabia with seamless city-to-city transitions.',
    feat6Title: '24/7 Available',
    feat6Desc: 'Plan your dream trip anytime, anywhere. No waiting, no appointments needed.',

    // How it works
    howItWorks: 'How Shawaf Works',
    step1: 'Create Your Account',
    step1Desc: 'Sign up and set your personal interests and preferences.',
    step2: 'Build Your Trip',
    step2Desc: 'Add your destinations, dates, budget, and activity preferences.',
    step3: 'Generate Itinerary',
    step3Desc: 'Our AI instantly generates a detailed daily travel plan.',
    step4: 'Explore & Enjoy',
    step4Desc: 'Use the interactive map, export PDF, and enjoy your next journey.',

    // Testimonials
    travelers_say: 'What Travelers Say',
    t1: '"Shawaf planned my 5-day Riyadh trip perfectly. The AI understood exactly what I wanted!"',
    t1Name: 'Khalid Al-Mansour',
    t1City: 'Riyadh',
    t2: '"The interactive map feature is amazing. I could see all my planned stops at a glance."',
    t2Name: 'Sara Al-Otaibi',
    t2City: 'Jeddah',
    t3: '"Generated a complete Al-Ula itinerary in seconds. Saved me hours of research!"',
    t3Name: 'Mohammed Bin Nasser',
    t3City: 'Al-Ula',

    // CTA
    ctaTitle: 'Ready to Explore Saudi Arabia?',
    ctaSub: 'Join thousands of travelers planning smart with Shawaf.',
    ctaBtn: 'Start Planning Your Trip →',

    // Footer
    footerDesc: 'AI-powered travel planning for Saudi Arabia. Aligned with Vision 2030.',
    vision2030: '✦ Aligned with Vision 2030',
    quickLinks: 'Quick Links',
    account: 'Account',
    contactUs: 'Contact Us',
    privacy: 'Privacy Policy',
    terms: 'Terms of Service',

    // Auth
    signInTitle: 'Sign In',
    signUpTitle: 'Create Account',
    emailAddress: 'Email Address',
    password: 'Password',
    forgotPassword: 'Forgot Password?',
    rememberMe: 'Remember Me',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    fullName: 'Full Name',

    // Planner
    planNewTrip: 'Plan a New Trip',
    step1Label: 'Trip Details',
    step2Label: 'Preferences',
    step3Label: 'Itinerary',
    step1Sub: 'Step 1 of 3: Basic trip information',
    step2Sub: 'Step 2 of 3: Your preferences',
    destinationCity: 'Destination City',
    searchCity: 'Search for a city...',
    startDate: 'Start Date',
    endDate: 'End Date',
    numberOfPeople: 'Number of People',
    tripType: 'Trip Type',
    configureTrip: 'Configure Trip →',
    tripDayCount: (n) => `📅 ${n} day${n !== 1 ? 's' : ''} trip`,

    cultural: 'Cultural & Heritage',
    adventure: 'Adventure & Outdoor',
    relaxation: 'Relaxation & Leisure',
    religious: 'Religious & Spiritual',
    business: 'Business & Tourism',
    family: 'Family Trip',

    budgetRange: 'Budget Range (SAR)',
    budget: 'Budget',
    midRange: 'Mid-Range',
    luxury: 'Luxury',
    activityLevel: 'Activity Level',
    low: 'Low',
    moderate: 'Moderate',
    high: 'High',
    activityTypes: 'Activity Types',
    selectAllInterest: 'Select all that interest you',
    sightseeing: 'Sightseeing',
    localDining: 'Local Dining',
    shopping: 'Shopping',
    museums: 'Museums',
    natureParks: 'Nature & Parks',
    sportsAdventure: 'Sports & Adventure',
    entertainment: 'Entertainment',
    photography: 'Photography Spots',
    accommodationType: 'Accommodation Type',
    budgetHotel: 'Budget Hotel',
    boutiqueHotel: 'Boutique Hotel',
    fiveStarHotel: '5-Star Hotel',
    resort: 'Resort',
    vacationRental: 'Vacation Rental',
    transportation: 'Transportation',
    rentalCar: 'Rental Car',
    taxiRide: 'Taxi / Ride-share',
    publicTransport: 'Public Transport',
    privateDriver: 'Private Driver',
    preferredTime: 'Preferred Time',
    morning: 'Morning',
    afternoon: 'Afternoon',
    evening: 'Evening',
    noPreference: 'No Preference',
    travelWith: 'Traveling With',
    alone: 'Alone',
    friends: 'Friends',
    familyGroup: 'Family',
    familyKids: 'Family with Kids',
    additionalNotes: 'Additional Notes',
    notesPlaceholder: 'Any special requirements or preferences...',
    generateItinerary: 'Generate Itinerary →',
    back: '← Back',

    // Itinerary
    tripSummary: 'Trip Summary',
    destinationCityLabel: 'Destination City:',
    startDateLabel: 'Start Date:',
    endDateLabel: 'End Date:',
    numberOfPeopleLabel: 'Number of People:',
    generatePDF: 'Generate PDF',
    saveTrip: 'Save Trip',
    regenerate: 'Regenerate Plan',
    backToPlanner: '← Back to Planner',
    openInMaps: 'Open in Maps',
    generating: 'Generating your itinerary...',
    generatingDesc: 'AI is crafting your perfect trip. This may take a few moments.',
    saving: 'Saving...',
    tripSaved: 'Trip saved successfully!',
    day: 'Day',

    // Map
    mapTitle: 'Trip Map Visualization',
    allAttractions: 'All Attractions',
    legend: 'Legend',
    attractions: 'Attractions',
    filterByDay: 'Filter by Day',
    noTripData: 'No trip data. Generate an itinerary first.',

    // Profile
    myProfile: 'My Profile',
    savedTrips: 'Saved Trips',
    updateProfile: 'Update Profile',
    noTripsYet: 'No saved trips yet.',
    startFirstTrip: 'Start Planning Your First Trip',
    viewItinerary: 'View Itinerary',
    deleteTrip: 'Delete',
    profileUpdated: 'Profile updated!',

    // Admin
    systemOverview: 'System Overview',
    activeTrips: 'Active Trips',
    aiAccuracy: 'AI Accuracy',
    newSignups: 'New Signups',
    totalRevenue: 'Total Revenue',
    analyticsTitle: 'Analytics — Trips Generated',
    recentActivity: 'Recent Activity',
    users: 'Users',
    name: 'Name',
    email: 'Email',
    trips_count: 'Trips',
    status: 'Status',
    active: 'Active',
    premium: 'Premium',
    inactive: 'Inactive',
  },

  ar: {
    home: 'الرئيسية',
    tripPlanner: 'تخطيط الرحلة',
    itinerary: 'جدول الرحلة',
    map: 'الخريطة',
    profile: 'الملف الشخصي',
    signIn: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    signOut: 'تسجيل الخروج',
    arabic: 'عربي',
    english: 'English',

    heroTag: '⚡ تخطيط سياحي بالذكاء الاصطناعي',
    heroTitle: 'خطط لرحلتك المثالية في المملكة العربية السعودية بالذكاء الاصطناعي',
    heroBrand: 'Shawaf – شواف',
    heroSub: 'استمتع بتخطيط سفر ذكي ومخصص بأحدث تقنيات الذكاء الاصطناعي. أنشئ جداول رحلات مفصلة يومية مع تفضيلاتك وميزانيتك واهتماماتك في المملكة العربية السعودية.',
    startPlanning: 'ابدأ تخطيط رحلتك ←',
    learnMore: 'اعرف المزيد',
    rating: '4.9',
    ratingLabel: 'تقييم المستخدم',
    cities: '+30',
    citiesLabel: 'مدينة مشمولة',
    travelers: '+12K',
    travelersLabel: 'مسافر سعيد',
    trips: '+50K',
    tripsLabel: 'رحلة مُولَّدة',

    whyChoose: 'لماذا تختار شواف؟',
    feat1Title: 'تخطيط بالذكاء الاصطناعي',
    feat1Desc: 'يولّد الذكاء الاصطناعي المتقدم لدينا خططاً مخصصة بناءً على تفضيلاتك الفريدة وأسلوب سفرك وميزانيتك.',
    feat2Title: 'خرائط تفاعلية',
    feat2Desc: 'تصوّر رحلتك بخرائط متكاملة تُظهر جميع المعالم والمسافات والطرق المثلى.',
    feat3Title: 'جدولة ذكية',
    feat3Desc: 'تحسين جدولك تلقائياً بناءً على أوقات الفتح وأوقات السفر وأولويات المعالم.',
    feat4Title: 'تصدير PDF',
    feat4Desc: 'نزّل خطة رحلتك الكاملة كملف PDF منسّق بشكل جميل لتأخذه معك في أي مكان.',
    feat5Title: 'رحلات متعددة المدن',
    feat5Desc: 'خطّط لرحلات معقدة عبر مدن المملكة بانتقالات سلسة بين المدن.',
    feat6Title: 'متاح 24/7',
    feat6Desc: 'خطّط لرحلة أحلامك في أي وقت وأي مكان. لا انتظار ولا مواعيد.',

    howItWorks: 'كيف يعمل شواف',
    step1: 'إنشاء حسابك',
    step1Desc: 'سجّل واضبط ملفك الشخصي مع اهتماماتك وتفضيلاتك.',
    step2: 'تكوين رحلتك',
    step2Desc: 'أدخل وجهاتك والتواريخ والميزانية وتفضيلات الأنشطة.',
    step3: 'توليد الجدول',
    step3Desc: 'يُنشئ ذكاؤنا الاصطناعي فوراً خطة سفر يومية مفصلة ومحسّنة.',
    step4: 'استكشف واستمتع',
    step4Desc: 'استخدم الخريطة التفاعلية، صدّر ملف PDF، واستمتع برحلتك المثالية.',

    travelers_say: 'ماذا يقول المسافرون',
    t1: '"خطّط شواف رحلتي لمدة 5 أيام في الرياض بشكل مثالي. فهم الاصطناعي بالضبط ما أريده."',
    t1Name: 'خالد المنصور',
    t1City: 'Riyadh',
    t2: '"ميزة الخريطة التفاعلية رائعة. استطعت رؤية جميع محطاتي المخططة في لمحة واحدة."',
    t2Name: 'سارة العتيبي',
    t2City: 'Jeddah',
    t3: '"ولّد جدول رحلة كاملاً للعُلا في ثوانٍ. وفّر علي ساعات من البحث."',
    t3Name: 'محمد بن ناصر',
    t3City: 'Al-Ula',

    ctaTitle: 'هل أنت مستعد لاستكشاف المملكة؟',
    ctaSub: 'انضم إلى آلاف المسافرين الذين يخططون بذكاء مع شواف.',
    ctaBtn: 'ابدأ تخطيط رحلتك ←',

    footerDesc: 'تخطيط سياحي بالذكاء الاصطناعي للمملكة العربية السعودية. متوافق مع رؤية 2030.',
    vision2030: '✦ متوافق مع رؤية 2030',
    quickLinks: 'روابط سريعة',
    account: 'الحساب',
    contactUs: 'تواصل معنا',
    privacy: 'سياسة الخصوصية',
    terms: 'شروط الخدمة',

    signInTitle: 'تسجيل الدخول',
    signUpTitle: 'إنشاء حساب',
    emailAddress: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    forgotPassword: 'نسيت كلمة المرور؟',
    rememberMe: 'تذكرني',
    noAccount: 'ليس لديك حساب؟',
    haveAccount: 'لديك حساب بالفعل؟',
    fullName: 'الاسم الكامل',

    planNewTrip: 'خطط لرحلة جديدة',
    step1Label: 'تفاصيل الرحلة',
    step2Label: 'التفضيلات',
    step3Label: 'الجدول',
    step1Sub: 'الخطوة 1 من 3: معلومات أساسية',
    step2Sub: 'الخطوة 2 من 3: تفضيلاتك',
    destinationCity: 'مدينة الوجهة',
    searchCity: 'ابحث عن مدينة...',
    startDate: 'تاريخ البدء',
    endDate: 'تاريخ الانتهاء',
    numberOfPeople: 'عدد الأشخاص',
    tripType: 'نوع الرحلة',
    configureTrip: 'تهيئة الرحلة →',
    tripDayCount: (n) => `📅 رحلة ${n} ${n === 1 ? 'يوم' : 'أيام'}`,

    cultural: 'ثقافي وتراثي',
    adventure: 'مغامرة وطبيعة',
    relaxation: 'استرخاء وترفيه',
    religious: 'ديني وروحاني',
    business: 'أعمال وسياحة',
    family: 'رحلة عائلية',

    budgetRange: 'نطاق الميزانية (ريال)',
    budget: 'اقتصادي',
    midRange: 'متوسط',
    luxury: 'فاخر',
    activityLevel: 'مستوى النشاط',
    low: 'منخفض',
    moderate: 'متوسط',
    high: 'مرتفع',
    activityTypes: 'أنواع الأنشطة',
    selectAllInterest: 'اختر كل ما يهمك',
    sightseeing: 'معالم سياحية',
    localDining: 'مطاعم محلية',
    shopping: 'تسوق',
    museums: 'متاحف',
    natureParks: 'طبيعة وحدائق',
    sportsAdventure: 'رياضة ومغامرة',
    entertainment: 'ترفيه',
    photography: 'تصوير',
    accommodationType: 'نوع الإقامة',
    budgetHotel: 'فندق اقتصادي',
    boutiqueHotel: 'فندق بوتيك',
    fiveStarHotel: 'فندق 5 نجوم',
    resort: 'منتجع',
    vacationRental: 'إيجار عطلة',
    transportation: 'المواصلات',
    rentalCar: 'سيارة إيجار',
    taxiRide: 'تاكسي / أوبر',
    publicTransport: 'مواصلات عامة',
    privateDriver: 'سائق خاص',
    preferredTime: 'الوقت المفضل',
    morning: 'صباح',
    afternoon: 'ظهر',
    evening: 'مساء',
    noPreference: 'لا تفضيل',
    travelWith: 'السفر مع',
    alone: 'بمفردي',
    friends: 'أصدقاء',
    familyGroup: 'عائلة',
    familyKids: 'عائلة مع أطفال',
    additionalNotes: 'ملاحظات إضافية',
    notesPlaceholder: 'أي متطلبات أو تفضيلات خاصة...',
    generateItinerary: 'توليد الجدول ←',
    back: '→ رجوع',

    tripSummary: 'ملخص الرحلة',
    destinationCityLabel: 'مدينة الوجهة:',
    startDateLabel: 'تاريخ البدء:',
    endDateLabel: 'تاريخ الانتهاء:',
    numberOfPeopleLabel: 'عدد الأشخاص:',
    generatePDF: 'تحميل PDF',
    saveTrip: 'حفظ الرحلة',
    regenerate: 'إعادة التوليد',
    backToPlanner: '→ العودة للمخطط',
    openInMaps: 'فتح في الخرائط',
    generating: 'جارٍ توليد جدولك...',
    generatingDesc: 'الذكاء الاصطناعي يصمم رحلتك المثالية. قد يستغرق هذا لحظات.',
    saving: 'جارٍ الحفظ...',
    tripSaved: 'تم حفظ الرحلة بنجاح!',
    day: 'اليوم',

    mapTitle: 'خريطة الرحلة',
    allAttractions: 'جميع المعالم',
    legend: 'المفتاح',
    attractions: 'معالم',
    filterByDay: 'تصفية حسب اليوم',
    noTripData: 'لا توجد بيانات رحلة. أنشئ جدولاً أولاً.',

    myProfile: 'ملفي الشخصي',
    savedTrips: 'الرحلات المحفوظة',
    updateProfile: 'تحديث الملف',
    noTripsYet: 'لا توجد رحلات محفوظة بعد.',
    startFirstTrip: 'ابدأ تخطيط أول رحلة',
    viewItinerary: 'عرض الجدول',
    deleteTrip: 'حذف',
    profileUpdated: 'تم تحديث الملف!',

    systemOverview: 'نظرة عامة على النظام',
    activeTrips: 'رحلات نشطة',
    aiAccuracy: 'دقة الذكاء الاصطناعي',
    newSignups: 'تسجيلات جديدة',
    totalRevenue: 'إجمالي الإيرادات',
    analyticsTitle: 'تحليلات — الرحلات المُولَّدة',
    recentActivity: 'النشاط الأخير',
    users: 'المستخدمون',
    name: 'الاسم',
    email: 'البريد',
    trips_count: 'رحلات',
    status: 'الحالة',
    active: 'نشط',
    premium: 'مميز',
    inactive: 'غير نشط',
  },
}

const LanguageContext = createContext({})

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'en')

  useEffect(() => {
    localStorage.setItem('lang', lang)
    document.documentElement.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr')
    document.documentElement.setAttribute('lang', lang)
  }, [lang])

  const toggle = () => setLang(l => l === 'en' ? 'ar' : 'en')

  const t = (key, ...args) => {
    const val = translations[lang][key]
    if (typeof val === 'function') return val(...args)
    return val ?? key
  }

  const isRTL = lang === 'ar'

  return (
    <LanguageContext.Provider value={{ lang, toggle, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLang = () => useContext(LanguageContext)
